# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/my19aac/Desktop/evosnns

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/my19aac/Desktop/evosnns

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/my19aac/Desktop/evosnns/CMakeFiles /Users/my19aac/Desktop/evosnns//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/my19aac/Desktop/evosnns/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Evosnn2

# Build rule for target.
Evosnn2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Evosnn2
.PHONY : Evosnn2

# fast build rule for target.
Evosnn2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/build
.PHONY : Evosnn2/fast

ComputationalUnit.o: ComputationalUnit.cpp.o
.PHONY : ComputationalUnit.o

# target to build an object file
ComputationalUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/ComputationalUnit.cpp.o
.PHONY : ComputationalUnit.cpp.o

ComputationalUnit.i: ComputationalUnit.cpp.i
.PHONY : ComputationalUnit.i

# target to preprocess a source file
ComputationalUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/ComputationalUnit.cpp.i
.PHONY : ComputationalUnit.cpp.i

ComputationalUnit.s: ComputationalUnit.cpp.s
.PHONY : ComputationalUnit.s

# target to generate assembly for a file
ComputationalUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/ComputationalUnit.cpp.s
.PHONY : ComputationalUnit.cpp.s

Evosnn.o: Evosnn.cpp.o
.PHONY : Evosnn.o

# target to build an object file
Evosnn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Evosnn.cpp.o
.PHONY : Evosnn.cpp.o

Evosnn.i: Evosnn.cpp.i
.PHONY : Evosnn.i

# target to preprocess a source file
Evosnn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Evosnn.cpp.i
.PHONY : Evosnn.cpp.i

Evosnn.s: Evosnn.cpp.s
.PHONY : Evosnn.s

# target to generate assembly for a file
Evosnn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Evosnn.cpp.s
.PHONY : Evosnn.cpp.s

Ga.o: Ga.cpp.o
.PHONY : Ga.o

# target to build an object file
Ga.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Ga.cpp.o
.PHONY : Ga.cpp.o

Ga.i: Ga.cpp.i
.PHONY : Ga.i

# target to preprocess a source file
Ga.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Ga.cpp.i
.PHONY : Ga.cpp.i

Ga.s: Ga.cpp.s
.PHONY : Ga.s

# target to generate assembly for a file
Ga.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Ga.cpp.s
.PHONY : Ga.cpp.s

Individual.o: Individual.cpp.o
.PHONY : Individual.o

# target to build an object file
Individual.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Individual.cpp.o
.PHONY : Individual.cpp.o

Individual.i: Individual.cpp.i
.PHONY : Individual.i

# target to preprocess a source file
Individual.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Individual.cpp.i
.PHONY : Individual.cpp.i

Individual.s: Individual.cpp.s
.PHONY : Individual.s

# target to generate assembly for a file
Individual.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Individual.cpp.s
.PHONY : Individual.cpp.s

Neuron.o: Neuron.cpp.o
.PHONY : Neuron.o

# target to build an object file
Neuron.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Neuron.cpp.o
.PHONY : Neuron.cpp.o

Neuron.i: Neuron.cpp.i
.PHONY : Neuron.i

# target to preprocess a source file
Neuron.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Neuron.cpp.i
.PHONY : Neuron.cpp.i

Neuron.s: Neuron.cpp.s
.PHONY : Neuron.s

# target to generate assembly for a file
Neuron.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Neuron.cpp.s
.PHONY : Neuron.cpp.s

Parameters.o: Parameters.cpp.o
.PHONY : Parameters.o

# target to build an object file
Parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Parameters.cpp.o
.PHONY : Parameters.cpp.o

Parameters.i: Parameters.cpp.i
.PHONY : Parameters.i

# target to preprocess a source file
Parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Parameters.cpp.i
.PHONY : Parameters.cpp.i

Parameters.s: Parameters.cpp.s
.PHONY : Parameters.s

# target to generate assembly for a file
Parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/Parameters.cpp.s
.PHONY : Parameters.cpp.s

UtilityFunctions.o: UtilityFunctions.cpp.o
.PHONY : UtilityFunctions.o

# target to build an object file
UtilityFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/UtilityFunctions.cpp.o
.PHONY : UtilityFunctions.cpp.o

UtilityFunctions.i: UtilityFunctions.cpp.i
.PHONY : UtilityFunctions.i

# target to preprocess a source file
UtilityFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/UtilityFunctions.cpp.i
.PHONY : UtilityFunctions.cpp.i

UtilityFunctions.s: UtilityFunctions.cpp.s
.PHONY : UtilityFunctions.s

# target to generate assembly for a file
UtilityFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/UtilityFunctions.cpp.s
.PHONY : UtilityFunctions.cpp.s

typedefs.o: typedefs.cpp.o
.PHONY : typedefs.o

# target to build an object file
typedefs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/typedefs.cpp.o
.PHONY : typedefs.cpp.o

typedefs.i: typedefs.cpp.i
.PHONY : typedefs.i

# target to preprocess a source file
typedefs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/typedefs.cpp.i
.PHONY : typedefs.cpp.i

typedefs.s: typedefs.cpp.s
.PHONY : typedefs.s

# target to generate assembly for a file
typedefs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Evosnn2.dir/build.make CMakeFiles/Evosnn2.dir/typedefs.cpp.s
.PHONY : typedefs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Evosnn2"
	@echo "... ComputationalUnit.o"
	@echo "... ComputationalUnit.i"
	@echo "... ComputationalUnit.s"
	@echo "... Evosnn.o"
	@echo "... Evosnn.i"
	@echo "... Evosnn.s"
	@echo "... Ga.o"
	@echo "... Ga.i"
	@echo "... Ga.s"
	@echo "... Individual.o"
	@echo "... Individual.i"
	@echo "... Individual.s"
	@echo "... Neuron.o"
	@echo "... Neuron.i"
	@echo "... Neuron.s"
	@echo "... Parameters.o"
	@echo "... Parameters.i"
	@echo "... Parameters.s"
	@echo "... UtilityFunctions.o"
	@echo "... UtilityFunctions.i"
	@echo "... UtilityFunctions.s"
	@echo "... typedefs.o"
	@echo "... typedefs.i"
	@echo "... typedefs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

